modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
issueTrackerURL="https://github.com/Mrthomas20121-Mods/TFC-Metalwork/issues"

[[mods]]
modId="tfc_metalwork"
version="0.0.7"
displayName="TFC Metalwork"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tfc_metalwork"
authors="Mrthomas20121"
description='''
Add metals and ores from other mods to TFC.
'''

[[dependencies.tfc_metalwork]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.tfc_metalwork]]
    modId="tfc"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.tfc_metalwork]]
    modId="tfc_metallum"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.tfc_metalwork]]
    modId="firmalife"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"